models/Eventos.php
<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "eventos".
 *
 * @property int $id
 * @property string|null $fecha_evento_creado
 * @property string|null $fecha_evento
 * @property string|null $hora_evento
 * @property string|null $descripcion
 * @property string|null $foto
 * @property string $estado_evento
 * @property int|null $usuario_id
 * @property int|null $playas_id
 *
 * @property Playas $playas
 * @property Usuarios $usuario
 */
class Eventos extends \yii\db\ActiveRecord
{
    public $imageFile;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'eventos';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['fecha_evento_creado', 'fecha_evento', 'hora_evento'], 'safe'],
            [['estado_evento'], 'required'],
            [['estado_evento'], 'string'],
            [['usuario_id', 'playas_id'], 'integer'],
            [['descripcion', 'foto'], 'string', 'max' => 500],
            [['playas_id'], 'exist', 'skipOnError' => true, 'targetClass' => Playas::class, 'targetAttribute' => ['playas_id' => 'id']],
            [['usuario_id'], 'exist', 'skipOnError' => true, 'targetClass' => Usuarios::class, 'targetAttribute' => ['usuario_id' => 'id']],
            [['foto'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, jpeg, webp', 'maxSize' => 1024 * 1024 * 2, 'tooBig' => 'El tamaño máximo permitido es de 2MB.'],
            [['imageFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, jpeg, webp', 'maxSize' => 1024 * 1024 * 2, 'tooBig' => 'El tamaño máximo permitido es de 2MB.'],
        ];
    }



    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'fecha_evento_creado' => 'Fecha Evento Creado',
            'fecha_evento' => 'Fecha Evento',
            'hora_evento' => 'Hora Evento',
            'descripcion' => 'Descripcion',
            'foto' => 'Foto',
            'estado_evento' => 'Estado Evento',
            'usuario_id' => 'Usuario ID',
            'playas_id' => 'Playas ID',
            'imageFile' => 'Imagen del Evento',
        ];
    }

    /**
     * Gets query for [[Playas]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPlayas()
    {
        return $this->hasOne(Playas::class, ['id' => 'playas_id']);
    }

    /**
     * Gets query for [[Usuario]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUsuario()
    {
        return $this->hasOne(Usuarios::class, ['id' => 'usuario_id']);
    }

    /**
     * Upload image and return its relative path.
     *
     * @return string|false the relative path of the uploaded image or false if upload failed
     */
    public function upload()
    {
        if ($this->validate() && $this->imageFile) {
            $directory = Yii::getAlias('@webroot') . '/img/upload-event/';
            if (!is_dir($directory)) {
                mkdir($directory, 0777, true);
            }

            $filePath = $directory . $this->imageFile->baseName . '.' . $this->imageFile->extension;

            if ($this->imageFile->saveAs($filePath)) {
                $this->foto = 'img/upload-event/' . $this->imageFile->baseName . '.' . $this->imageFile->extension;
                return true;
            }
        }
        return false;
    }
}

controllers/BlogController.php
<?php

namespace app\controllers;

use app\models\Blog;
use app\models\Comentarios;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use Yii;

class BlogController extends Controller
{
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    public function actionIndex()
    {
        $query = Blog::find();
        $blogs = $query->orderBy(['fecha_creacion' => SORT_DESC])->all();
        $categories = Blog::getAvailableCategories();

        $model = new Blog();
        $user = Yii::$app->user->identity;

        $ultimosTresBlogs = array_slice($blogs, 0, 3);

        $comentariosCount = [];
        foreach ($blogs as $blog) {
            $comentariosCount[$blog->id] = Comentarios::find()->where(['blog_id' => $blog->id])->count();
        }

        return $this->render('index', [
            'blogs' => $blogs,
            'model' => $model,
            'user' => $user,
            'categories' => $categories,
            'ultimosTresBlogs' => $ultimosTresBlogs,
            'comentariosCount' => $comentariosCount,
        ]);
    }

    public function actionView($id)
    {
        $blog = $this->findModel($id);
        $comentarios = Comentarios::find()->where(['blog_id' => $id])->all();
        $comentariosCount = count($comentarios);

        $query = Blog::find();
        $blogs = $query->orderBy(['fecha_creacion' => SORT_DESC])->all();
        $categories = Blog::getAvailableCategories();

        $ultimosTresBlogs = array_slice($blogs, 0, 3);

        return $this->render('view', [
            'blog' => $blog,
            'comentarios' => $comentarios,
            'comentariosCount' => $comentariosCount,
            'categories' => $categories,
            'ultimosTresBlogs' => $ultimosTresBlogs,
        ]);
    }

    public function actionCreate()
    {
        $model = new Blog();

        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {
                $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
                if ($model->validate()) {
                    $rutaImagen = $model->upload();
                    if ($rutaImagen !== false) {
                        $model->imagen = $rutaImagen;
                        if ($model->save()) {
                            return $this->redirect(['view', 'id' => $model->id]);
                        }
                    }
                }
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $currentImage = $model->imagen;

        if ($this->request->isPost) {
            $postData = $this->request->post();
            $model->load($postData);

            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            if ($model->imageFile) {
                if ($model->validate() && $rutaImagen = $model->upload()) {
                    $model->imagen = $rutaImagen;
                } else {
                    $model->imagen = $currentImage; 
                }
            } else {
                $model->imagen = $currentImage; 
            }

            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        if (($model = Blog::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/EventosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Eventos;
use app\models\Playas;
use app\models\Blog;

use yii\web\Controller;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\ArrayHelper;
use yii\web\ForbiddenHttpException;

/**
 * EventosController implements the CRUD actions for Eventos model.
 */
class EventosController extends Controller
{
    public $imageFile;

    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Eventos models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Eventos::find(),
        ]);

        $eventos = Eventos::find()->all();

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'eventos' => $eventos,
        ]);
    }

    /**
     * Displays a single Eventos model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $playa = $model->playas;
    
        // Obtener los últimos eventos, ordenados por fecha en orden descendente
        $ultimosEventos = Eventos::find()
            ->orderBy(['fecha_evento_creado' => SORT_ASC])
            ->limit(3)
            ->all();
    
        return $this->render('view', [
            'model' => $model,
            'playa' => $playa,
            'ultimosEventos' => $ultimosEventos,
        ]);
    }
    




    /**
     * Creates a new Eventos model.
     * If creation is successful, the browser will be redirected to the 'index' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        if (Yii::$app->user->isGuest || Yii::$app->user->identity->rol !== 'administrador') {
            throw new ForbiddenHttpException('No tienes permiso para acceder a esta página.');
        }

        $model = new Eventos();

        if ($model->load(Yii::$app->request->post())) {
            $model->fecha_evento_creado = date('Y-m-d H:i:s');
            $model->usuario_id = Yii::$app->user->id;

            // Procesar la imagen subida
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            if ($model->imageFile && !$model->upload()) {
                Yii::$app->session->setFlash('error', 'Error al subir la imagen.');
                return $this->render('create', [
                    'model' => $model,
                ]);
            }

            // Combinar la fecha y la hora del evento
            if (!empty($model->fecha_evento) && !empty($model->hora_evento)) {
                $fechaHora = \DateTime::createFromFormat('d-m-Y H:i', $model->fecha_evento . ' ' . $model->hora_evento);
                if ($fechaHora) {
                    $model->fecha_evento = $fechaHora->format('Y-m-d H:i:s');
                } else {
                    Yii::$app->session->setFlash('error', 'Fecha y hora del evento no válidas.');
                    return $this->render('create', [
                        'model' => $model,
                    ]);
                }
            }

            if ($model->save(false)) {
                Yii::$app->session->setFlash('success', 'Evento creado con éxito.');
                return $this->redirect(['index']);
            } else {
                Yii::$app->session->setFlash('error', 'Error al guardar el evento.');
            }
        }

        $playas = Playas::find()->select(['id', 'nombre', 'ubicacion'])->all();
        $playasList = ArrayHelper::map($playas, 'id', 'nombre');

        return $this->render('create', [
            'model' => $model,
            'playasList' => $playasList,
        ]);
    }








    /**
     * Updates an existing Eventos model.
     * If update is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        // Guardar la fecha y hora originales antes de cargar los nuevos datos
        $originalFechaEvento = $model->fecha_evento;
        $originalHoraEvento = $model->hora_evento;

        if ($model->load(Yii::$app->request->post())) {

            $model->fecha_evento_creado = date('Y-m-d H:i:s');
            $model->usuario_id = Yii::$app->user->id;

            // Procesar la imagen subida
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            if ($model->imageFile && !$model->upload()) {
                Yii::$app->session->setFlash('error', 'Error al subir la imagen.');
                return $this->render('update', [
                    'model' => $model,
                ]);
            }

            // Verificar si la fecha del evento no se modificó, mantener la fecha original
            if (empty($model->fecha_evento)) {
                $model->fecha_evento = $originalFechaEvento;
            } else {
                // Convertir fecha a formato 'Y-m-d'
                $fecha = \DateTime::createFromFormat('d-m-Y', $model->fecha_evento);
                if ($fecha) {
                    $model->fecha_evento = $fecha->format('Y-m-d');
                } else {
                    Yii::$app->session->setFlash('error', 'Fecha del evento no válida.');
                    return $this->render('update', [
                        'model' => $model,
                    ]);
                }
            }

            // Verificar si la hora del evento no se modificó, mantener la hora original
            if ($model->hora_evento === $originalHoraEvento || empty($model->hora_evento)) {
                $model->hora_evento = $originalHoraEvento;
            } else {
                // Verificar si la hora es válida
                if (preg_match('/^([01]\d|2[0-3]):([0-5]\d)$/', $model->hora_evento)) {
                    // La hora está en formato válido de 24 horas
                } else {
                    Yii::$app->session->setFlash('error', 'Hora del evento no válida.');
                    return $this->render('update', [
                        'model' => $model,
                    ]);
                }
            }

            
            if ($model->save(false)) {
                Yii::$app->session->setFlash('success', 'Evento actualizado con éxito.');
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                Yii::$app->session->setFlash('error', 'Error al guardar el evento.');
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }











    /**
     * Deletes an existing Eventos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Eventos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Eventos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Eventos::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/eventos/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;
use yii\helpers\ArrayHelper;
use app\models\Playas;

/* @var $this yii\web\View */
/* @var $model app\models\Eventos */
/* @var $form yii\widgets\ActiveForm */

$playas = Playas::find()->select(['id', 'nombre', 'ubicacion'])->all();
$playasList = ArrayHelper::map($playas, 'id', 'nombre');
?>

<div class="eventos-form container p-5">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

            <!-- Campo para mostrar la vista previa de la imagen -->
            <div class="profile-picture-container event-picture-container text-center">
                <h1 class="title"><?= $model->isNewRecord ? 'Crear evento' : 'Actualizar evento' ?></h1>
                <div class="profile-picture event-picture">
                    <?= Html::img($model->foto ? '@web/' . $model->foto : '@web/img/upload-event/event-default.jpg', [
                        'alt' => 'Imagen del evento',
                        'class' => 'img-update-event',
                        'id' => 'event-picture-preview',
                    ]) ?>
                    <div class="upload-button">
                        <?= Html::label('<i class="fas fa-camera"></i>', 'event-picture-input', ['class' => 'btn btn-upload']) ?>
                        <?= $form->field($model, 'imageFile')->fileInput([
                            'id' => 'event-picture-input',
                            'class' => 'd-none',
                        ])->label(false) ?>
                    </div>
                </div>
            </div>

            <!-- Playas Desplegable -->
            <?= $form->field($model, 'playas_id')->dropDownList($playasList, ['prompt' => 'Seleccione una playa', 'id' => 'playas-dropdown'])->label('Playas') ?>

            <!-- Ubicación -->
            <div class="form-group">
                <?= Html::label('Ubicación', 'ubicacion-field', ['class' => 'control-label']) ?>
                <?= Html::textInput('ubicacion', $model->playas ? $model->playas->ubicacion : '', ['class' => 'form-control', 'readonly' => true, 'id' => 'ubicacion-field']) ?>
            </div>

            <!-- Seleccionar Fecha -->
            <?= $form->field($model, 'fecha_evento')->widget(DatePicker::classname(), [
                'dateFormat' => 'dd-MM-yyyy',
                'options' => ['class' => 'form-control', 'readonly' => true],
                'clientOptions' => [
                    'minDate' => 0, // Permite seleccionar desde hoy
                    'maxDate' => '+2m', // Permite seleccionar 2 meses
                    'changeMonth' => true, // Permite la selección directa del mes
                    'changeYear' => false, // No permite cambiar de año
                    'yearRange' => '0:+0', // Rango de años permitidos
                    'theme' => 'base',
                    'placeholder' => 'Seleccione fecha',
                    'autocomplete' => 'off',
                ],
            ])->label('Fecha') ?>

            <!-- Seleccionar Hora -->
            <?= $form->field($model, 'hora_evento')->input('time', ['class' => 'form-control'])->label('Hora') ?>

            <div class="form-group">
                <label for="descripcion">Descripción</label>
                <small id="char-count" class="form-text text-muted">0/500 caracteres</small>
                <?= $form->field($model, 'descripcion')->textarea([
                    'rows' => 6,
                    'id' => 'descripcion',
                    'maxlength' => true,
                ])->label(false) ?>
            </div>

            <!-- Estado del Evento -->
            <?= $form->field($model, 'estado_evento')->dropDownList([
                'planificado' => 'Planificado',
                'en curso' => 'En Curso',
                'concluido' => 'Concluido',
            ])->label('Estado del Evento') ?>

            <div class="form-group">
                <?= Html::submitButton($model->isNewRecord ? 'Crear' : 'Actualizar', ['class' => 'btn btn-clean w-100']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

<script>
    // Asignar ubicaciones de playas a un objeto para fácil acceso
    var playas = <?= json_encode(ArrayHelper::map($playas, 'id', 'ubicacion')) ?>;

    document.getElementById('event-picture-input').addEventListener('change', function(event) {
        var preview = document.getElementById('event-picture-preview');
        var file = event.target.files[0];
        var reader = new FileReader();

        reader.onloadend = function() {
            preview.src = reader.result;
        };

        if (file) {
            reader.readAsDataURL(file);
        }
    });

    // Actualizar campo de ubicación cuando se seleccione una playa
    document.getElementById('playas-dropdown').addEventListener('change', function() {
        var playaId = this.value;
        var ubicacionField = document.getElementById('ubicacion-field');
        if (playas[playaId]) {
            ubicacionField.value = playas[playaId];
        } else {
            ubicacionField.value = '';
        }
    });

    document.addEventListener('DOMContentLoaded', function() {
        var textarea = document.getElementById('descripcion');
        var charCount = document.getElementById('char-count');

        // Inicializar el contador de caracteres al cargar la página
        var textLength = textarea.value.length;
        charCount.textContent = textLength + '/500 caracteres';

        // Actualizar el contador de caracteres en tiempo real
        textarea.addEventListener('input', function() {
            textLength = textarea.value.length;
            charCount.textContent = textLength + '/500 caracteres';
        });
    });
</script>

views/eventos/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ListView;

/** @var yii\web\View $this */
/** @var yii\data\ActiveDataProvider $dataProvider */
/** @var app\models\Eventos[] $eventos */

$this->title = 'Eventos';
?>

<div class="row">
    <div class="col banner-container p-0">
        <h1 class="title title-recursos">Próximos eventos</h1>
        <div class="overlay"></div>
        <?= Html::img('@web/img/banner1.webp', ['alt' => 'Banner Img Logo', 'class' => 'img-banner']) ?>
    </div>
</div>

<div class="eventos-index container">
    <div class="row">
        <div class="col">
            <?php if (!Yii::$app->user->isGuest && Yii::$app->user->identity->rol === 'administrador') : ?>
                <p>
                    <?= Html::a('Crear Evento', ['create'], ['class' => 'btn btn-clean']) ?>
                </p>
            <?php endif; ?>
        </div>
    </div>

    <div class="row">
        <?php foreach ($eventos as $evento) : ?>
            <div class="col-4 card-c">
                <a href="<?= Url::to(['view', 'id' => $evento->id]) ?>" class="card-link">
                    <div class="card shadow-sm">
                        <div class="img-evento-card">
                            <small class="estado-evento"><?= Html::encode($evento->estado_evento) ?></small>
                            <img src="<?= Url::to('@web/' . $evento->foto) ?>" class="bd-placeholder-img card-img-top" width="100%" height="225" alt="Imagen del evento" class="img-playa">

                            <?php if (!Yii::$app->user->isGuest && Yii::$app->user->identity->rol === 'administrador') : ?>
                                <div class="update-delete">
                                <!-- BTN ACTUALZIAR -->    
                                <a href="<?= Url::to(['update', 'id' => $evento->id]) ?>" class="btn btn-sm btn-outline-secondary bg-dark"><i class="fa-regular fa-pen-to-square text-success"></i></a>
                                    
                                    <!-- BTN ELIMINAR -->
                                    <a href="<?= Url::to(['delete', 'id' => $evento->id]) ?>" class="btn btn-sm btn-outline-secondary bg-dark" data-method="post" data-confirm="¿Estás seguro de eliminar este evento?"><i class="fa-regular fa-trash-can text-danger"></i></a>
                                </div>
                            <?php endif; ?>

                        </div>
                        <div class="card-body">
                            <h5 class="card-title"><?= Html::encode($evento->playas->nombre) ?></h5>
                            <div class="ubicacion d-flex align-items-center mb-2">
                                <i class="fa-solid fa-location-dot text-muted"></i>&nbsp;
                                <h6 class="card-subtitle mt-0 text-muted"><?= Html::encode($evento->playas->ubicacion) ?></h6>
                            </div>
                            <p class="card-text">
                                <i class="fa-regular fa-calendar"></i>
                                <small class="fecha-evento"><?= Html::encode(date('d-m-Y', strtotime($evento->fecha_evento))) ?></small>&nbsp;

                                <i class="fa-regular fa-clock"></i>
                                <small class="fecha-evento"><?= Html::encode((new \DateTime($evento->hora_evento))->format('H:i')) ?></small>
                            </p>
                            <p class="card-text mb-3"><?= Html::encode($evento->descripcion) ?></p>

                            <div class="d-flex align-items-center">
                                <div class="btn-group w-100 btn-view-card">
                                    <a href="<?= Url::to(['view', 'id' => $evento->id]) ?>" class="btn btn-clean w-100 btn-view">Ver</a>

                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
</div>

views/eventos/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Eventos $model */

?>
<div class="eventos-update">


    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/eventos/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var app\models\Eventos $model */
/** @var app\models\Playas $playa */

\yii\web\YiiAsset::register($this);
?>
<?php

use yii\helpers\Url;




/* CONVIERTE LA FECHA DE FORMATO A INGLES A ESPAÑOL */

setlocale(LC_TIME, 'es_ES.UTF-8');

$this->title = "Eventos";


?>

<!-- BANNER -->
<div class="row">
    <div class="col banner-container p-0">
        <h1 class="title title-recursos"><?= Html::encode($this->title) ?></h1>
        <div class="overlay"></div>
        <?= Html::img('@web/img/banner1.webp', ['alt' => 'Banner Img Logo', 'class' => 'img-banner']) ?>
    </div>
</div>

<div class="blog-index blog-view w-100">
    <div class="row">
        <div class="col px-0">
            <!-- ACTUALIZAR - BORRAR (ADM)-->
            <?php if (!Yii::$app->user->isGuest && Yii::$app->user->identity->rol === 'administrador') : ?>
                <div class="row my-3">
                    <div class="col">
                        <?= Html::a('Actualizar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                        <?= Html::a('Borrar', ['delete', 'id' => $model->id], [
                            'class' => 'btn btn-danger',
                            'data' => [
                                'confirm' => '¿Estás seguro de que deseas eliminar este elemento?',
                                'method' => 'post',
                            ],
                        ]) ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>

    <div class="row">
        <div class="col-8">

            <!-- CATEGORIA -->
            <a href="<?= Url::to(['blog/view', 'id' => $model->id]) ?>" class="btn btn-b btn-category my-4">
                <p class="card-text">
                    <small class="category"><?= Html::encode($model->estado_evento) ?></small>
                </p>
            </a>


            <h5 class="card-title"><?= Html::encode($playa->nombre) ?></h5>

            <!-- Ubicación -->
            <div class="ubicacion d-flex align-items-center mb-2">
                <i class="fa-solid fa-location-dot text-muted" style="font-size:24px;"></i>&nbsp;
                <?php if ($playa !== null) : ?>
                    <h6 class="card-subtitle mt-0 text-muted"><?= Html::encode($playa->ubicacion) ?></h6>
                <?php endif; ?>
            </div>

            <!-- FECHA y hora -->
            <p class="card-text date mb-4">
                Evento programado a
                <?= strftime('%e %B, %Y', strtotime($model->fecha_evento_creado)) ?>&nbsp;&nbsp;
                <i class="fa-regular fa-clock" style="font-size: 20px;"></i>
                <span class="fecha-evento"><?= Html::encode((new \DateTime($model->hora_evento))->format('H:i')) ?></span>
            </p>

            <!-- Mostrar la imagen -->
            <?php if ($model->foto) : ?>
                <?= Html::img(Url::to('@web/' . $model->foto), ['class' => 'blog-img card-img-top img-view', 'alt' => 'Imagen']) ?>
            <?php endif; ?>



            <h6 class="pt-4">Información</h6>

            <p class="mb-5">
                <?= Html::encode($model->descripcion) ?>
            </p>


        </div>

        <div class="col-4 c-2">


            <!-- Últimos Eventos Recientes -->
            <!-- Últimos Eventos Recientes -->
            <div class="b-2 mt-5">
                <h6>Próximos eventos</h6>
                <ul class="p-0 categorias-donar categorias-blog blog-reciente evento-reciente">
                    <?php foreach ($ultimosEventos as $evento) : ?>
                        <li class="d-flex align-items-center">
                            <!-- Mostrar la imagen del evento -->
                            <?php if ($evento->foto) : ?>
                                <?= Html::img(Url::to('@web/' . $evento->foto), ['class' => 'img-evento', 'alt' => 'Imagen del evento']) ?>
                            <?php endif; ?>
                            <h6 class="title-recent-blog text-center d-flex flex-column">
                                <?= Html::encode($evento->playas->nombre) ?>
                                <span class="date-event-view">
                                    <?= strftime('%e %B, %Y', strtotime($evento->fecha_evento)) ?>&nbsp;&nbsp;
                                    <i class="fa-regular fa-clock" style="font-size: 12px;"></i>
                                    <span class="fecha-evento"><?= Html::encode((new \DateTime($evento->hora_evento))->format('H:i')) ?></span>
                                </span>
                            </h6>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>




            <!-- MODAL -->
            <div class="b-3 mt-5">
                <h6>Galería</h6>
                <?= Html::img('@web/img/ocean.webp', ['class' => 'modal-img', 'alt' => 'Imagen 1']) ?>
                <?= Html::img('@web/img/limp-playa.webp', ['class' => 'modal-img', 'alt' => 'Imagen 2']) ?>
                <?= Html::img('@web/img/voluntariadov2.webp', ['class' => 'modal-img', 'alt' => 'Imagen 3']) ?>
                <?= Html::img('@web/img/limpieza-playa.webp', ['class' => 'modal-img', 'alt' => 'Imagen 1']) ?>
                <?= Html::img('@web/img/voluntariado.png', ['class' => 'modal-img', 'alt' => 'Imagen 2']) ?>
                <?= Html::img('@web/img/ocean.webp', ['class' => 'modal-img', 'alt' => 'Imagen 3']) ?>
                <!-- Modal -->
                <div id="myModal" class="modal">

                    <!-- Contenido del modal -->
                    <div class="modal-content">
                        <span class="close">&times;</span>
                        <img id="modalImage" src="" alt="">
                    </div>

                </div>
            </div>
        </div>


    </div>
</div>